#!/bin/sh
set -e

if [ -z $WORKSPACE ]
then
  WORKSPACE=$(pwd)
fi

docker run -it --rm \
  -p 4001:4001 \
  --env NEW_RELIC_APP_NAME=MY_SAMPLE_APP_NAME \
  --env NEW_RELIC_LICENSE_KEY=FANCY_LICENSE_KEY_HERE \
  --env NEW_RELIC_DATACENTER=MY_DATACENTER \
  --env NEW_RELIC_ENVIRONMENT=MY_ENVIRONMENT \
  --env NEW_RELIC_ROLETYPEID=MY_ROLE_TYPE_ID \
  --env TRAVEL_LOCATIONS_URI=http://FQDN_LOCATIONS_SERVICE \
  $*
